import optionsJson from '../../assets/options.json'

export const optionsData: any = optionsJson as any

export const genderOptions = optionsData.genderOptions ?? []
export const maritalStatusOptions = optionsData.maritalStatusOptions ?? []
export const yesNoUnknownOptions = optionsData.yesNoUnknownOptions ?? []
export const lifeStatusOptions = optionsData.lifeStatusOptions ?? []
export const degreeOptions = optionsData.degreeOptions ?? []
export const academicDegreeOptions = optionsData.academicDegreeOptions ?? []
export const educationTypeOptions = optionsData.educationTypeOptions ?? []
export const companyTypeOptions = optionsData.companyTypeOptions ?? []
export const workModeOptions = optionsData.workModeOptions ?? []
export const industryOptions = optionsData.industryOptions ?? []
export const hashtagCategories = optionsData.hashtagCategories ?? []
export const strengthsQuickOptions = optionsData.strengthsQuickOptions ?? []
export const weaknessesQuickOptions = optionsData.weaknessesQuickOptions ?? []
export const personalityOptions = optionsData.personalityOptions ?? []
export const socialPlatformOptions = optionsData.socialPlatformOptions ?? []
export const skillTreeData = optionsData.skillTreeData ?? []
export const certificateTreeData = optionsData.certificateTreeData ?? []
export const skillLevelOptions = optionsData.skillLevelOptions ?? []
export const languageNameOptions = optionsData.languageNameOptions ?? []
export const languageLevelOptions = optionsData.languageLevelOptions ?? []
export const artifactTypeOptions = optionsData.artifactTypeOptions ?? []
export const projectTypeOptions = optionsData.projectTypeOptions ?? []
export const techStackTreeData = optionsData.techStackTreeData ?? []
export const capabilityStackOptions = optionsData.capabilityStackOptions ?? []
export const speechLocationOptions = optionsData.speechLocationOptions ?? []
